### ISSUE TITLE
Create a branch per section

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/advanced-react-perf#14]
We need to step through the optimizations on `master` and apply them to `unoptimized-start` in sequence.

Notes on the sequence:

- Start with a mess

// Part 1: low-hanging fruit

- Run the bundle analyzer
- Turn on production builds for webpack
- Add terser
- Extract CSS
- Minify CSS
- Set browser targets for Babel (`@babel/preset-env`)
- Enable gzip compression

// Part 2: set up code splitting

- lazy load large deps (the Prettier + plugins setup)
- lazy load routes and large components (React.lazy + Suspense)
- add chunk names for easier debugging

// Part 3: refactor giant deps

- move Prettier to admin dashboard vs. loading on the client side
- refactor Moment.js to use `date-fns`

> to mention: lodash vs. lodash-es

// Part 4: optimize font loading

- switch from `@import` to `<link />` for Google fonts
- add `font-display: swap` for local fonts (Fira Code)

// Part 5: add a Service Worker

- set up workbox
- load the SW in `index.html`

> at this point, _all_ the bundles will be preloaded, and that’s ~1.5MB

- ignore vendor bundles
- set up runtime caching for vendor bundles
- add runtime caching for Google Fonts

// Part 6: show things as loaded instead of blocking on the slowest thing

- refactor the dashboard to load metrics inside the chart
- use Suspense to load the chart

// Part 7: optimize images 

- run JPGs and PNGs through tinypng.com (you can get an API key and do this automatically)
- optimize SVG with SVGO (we do this automatically with https://github.com/boopathi/react-svg-loader)

**Comment by siakaramalegos** [comment]
Looks good. Should we change the order of the slides to match? I can do that in a branch and then you can approve if you agree.

**Comment by siakaramalegos** [comment]
Add: preload of local fonts.

**Comment by siakaramalegos** [comment]
Do I need to do a PR to unoptimized just to set up webpack to load fonts?

**Comment by siakaramalegos** [comment]
Looks like 3rd party scripts got dropped. Just mentioning in case it was not intentional.

**Comment by jlengstorf** [comment]
This is all done — we dropped third-party scripts since the app wasn't set up with any. Given that the workshop ran a little short, I think it might be worth adding some so we're able to cover this.
